/* 
 * Library API
 *
 * Through this API you can access authors and their books.
 *
 * OpenAPI spec version: 1.0
 * Contact: kevin.dockx@gmail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing BookForCreationWithAmountOfPages
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class BookForCreationWithAmountOfPagesTests
    {
        // TODO uncomment below to declare an instance variable for BookForCreationWithAmountOfPages
        //private BookForCreationWithAmountOfPages instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of BookForCreationWithAmountOfPages
            //instance = new BookForCreationWithAmountOfPages();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of BookForCreationWithAmountOfPages
        /// </summary>
        [Test]
        public void BookForCreationWithAmountOfPagesInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" BookForCreationWithAmountOfPages
            //Assert.IsInstanceOfType<BookForCreationWithAmountOfPages> (instance, "variable 'instance' is a BookForCreationWithAmountOfPages");
        }


        /// <summary>
        /// Test the property 'AmountOfPages'
        /// </summary>
        [Test]
        public void AmountOfPagesTest()
        {
            // TODO unit test for the property 'AmountOfPages'
        }
        /// <summary>
        /// Test the property 'Title'
        /// </summary>
        [Test]
        public void TitleTest()
        {
            // TODO unit test for the property 'Title'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Test]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }

    }

}
