/* 
 * Library API
 *
 * Through this API you can access authors and their books.
 *
 * OpenAPI spec version: 1.0
 * Contact: kevin.dockx@gmail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using RestSharp;
using IO.Swagger.Client;
using IO.Swagger.Model;

namespace IO.Swagger.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
        public interface IAuthorsApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Get an author by his/her id
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="authorId">The id of the author you want to get</param>
        /// <returns>Author</returns>
        Author GetAuthor (Guid? authorId);

        /// <summary>
        /// Get an author by his/her id
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="authorId">The id of the author you want to get</param>
        /// <returns>ApiResponse of Author</returns>
        ApiResponse<Author> GetAuthorWithHttpInfo (Guid? authorId);
        /// <summary>
        /// Get a list of authors
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>List&lt;Author&gt;</returns>
        List<Author> GetAuthors ();

        /// <summary>
        /// Get a list of authors
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of List&lt;Author&gt;</returns>
        ApiResponse<List<Author>> GetAuthorsWithHttpInfo ();
        /// <summary>
        /// Update an author
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="authorId">The id of the author to update</param>
        /// <param name="body"> (optional)</param>
        /// <returns>Author</returns>
        Author UpdateAuthor (Guid? authorId, AuthorForUpdate body = null);

        /// <summary>
        /// Update an author
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="authorId">The id of the author to update</param>
        /// <param name="body"> (optional)</param>
        /// <returns>ApiResponse of Author</returns>
        ApiResponse<Author> UpdateAuthorWithHttpInfo (Guid? authorId, AuthorForUpdate body = null);
        /// <summary>
        /// Partially update an author
        /// </summary>
        /// <remarks>
        /// Sample request (this request updates the author&#x27;s **first name**)                              PATCH /authors/authorId              [                   {                      \&quot;op\&quot;: \&quot;replace\&quot;,                       \&quot;path\&quot;: \&quot;/firstname\&quot;,                       \&quot;value\&quot;: \&quot;new first name\&quot;                   }               ]
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="authorId">The id of the author you want to get</param>
        /// <param name="body"> (optional)</param>
        /// <returns>Author</returns>
        Author UpdateAuthor_0 (Guid? authorId, List<Operation> body = null);

        /// <summary>
        /// Partially update an author
        /// </summary>
        /// <remarks>
        /// Sample request (this request updates the author&#x27;s **first name**)                              PATCH /authors/authorId              [                   {                      \&quot;op\&quot;: \&quot;replace\&quot;,                       \&quot;path\&quot;: \&quot;/firstname\&quot;,                       \&quot;value\&quot;: \&quot;new first name\&quot;                   }               ]
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="authorId">The id of the author you want to get</param>
        /// <param name="body"> (optional)</param>
        /// <returns>ApiResponse of Author</returns>
        ApiResponse<Author> UpdateAuthor_0WithHttpInfo (Guid? authorId, List<Operation> body = null);
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// Get an author by his/her id
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="authorId">The id of the author you want to get</param>
        /// <returns>Task of Author</returns>
        System.Threading.Tasks.Task<Author> GetAuthorAsync (Guid? authorId);

        /// <summary>
        /// Get an author by his/her id
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="authorId">The id of the author you want to get</param>
        /// <returns>Task of ApiResponse (Author)</returns>
        System.Threading.Tasks.Task<ApiResponse<Author>> GetAuthorAsyncWithHttpInfo (Guid? authorId);
        /// <summary>
        /// Get a list of authors
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of List&lt;Author&gt;</returns>
        System.Threading.Tasks.Task<List<Author>> GetAuthorsAsync ();

        /// <summary>
        /// Get a list of authors
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of ApiResponse (List&lt;Author&gt;)</returns>
        System.Threading.Tasks.Task<ApiResponse<List<Author>>> GetAuthorsAsyncWithHttpInfo ();
        /// <summary>
        /// Update an author
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="authorId">The id of the author to update</param>
        /// <param name="body"> (optional)</param>
        /// <returns>Task of Author</returns>
        System.Threading.Tasks.Task<Author> UpdateAuthorAsync (Guid? authorId, AuthorForUpdate body = null);

        /// <summary>
        /// Update an author
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="authorId">The id of the author to update</param>
        /// <param name="body"> (optional)</param>
        /// <returns>Task of ApiResponse (Author)</returns>
        System.Threading.Tasks.Task<ApiResponse<Author>> UpdateAuthorAsyncWithHttpInfo (Guid? authorId, AuthorForUpdate body = null);
        /// <summary>
        /// Partially update an author
        /// </summary>
        /// <remarks>
        /// Sample request (this request updates the author&#x27;s **first name**)                              PATCH /authors/authorId              [                   {                      \&quot;op\&quot;: \&quot;replace\&quot;,                       \&quot;path\&quot;: \&quot;/firstname\&quot;,                       \&quot;value\&quot;: \&quot;new first name\&quot;                   }               ]
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="authorId">The id of the author you want to get</param>
        /// <param name="body"> (optional)</param>
        /// <returns>Task of Author</returns>
        System.Threading.Tasks.Task<Author> UpdateAuthor_0Async (Guid? authorId, List<Operation> body = null);

        /// <summary>
        /// Partially update an author
        /// </summary>
        /// <remarks>
        /// Sample request (this request updates the author&#x27;s **first name**)                              PATCH /authors/authorId              [                   {                      \&quot;op\&quot;: \&quot;replace\&quot;,                       \&quot;path\&quot;: \&quot;/firstname\&quot;,                       \&quot;value\&quot;: \&quot;new first name\&quot;                   }               ]
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="authorId">The id of the author you want to get</param>
        /// <param name="body"> (optional)</param>
        /// <returns>Task of ApiResponse (Author)</returns>
        System.Threading.Tasks.Task<ApiResponse<Author>> UpdateAuthor_0AsyncWithHttpInfo (Guid? authorId, List<Operation> body = null);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
        public partial class AuthorsApi : IAuthorsApi
    {
        private IO.Swagger.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="AuthorsApi"/> class.
        /// </summary>
        /// <returns></returns>
        public AuthorsApi(String basePath)
        {
            this.Configuration = new IO.Swagger.Client.Configuration { BasePath = basePath };

            ExceptionFactory = IO.Swagger.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="AuthorsApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public AuthorsApi(IO.Swagger.Client.Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = IO.Swagger.Client.Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = IO.Swagger.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public IO.Swagger.Client.Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public IO.Swagger.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public IDictionary<String, String> DefaultHeader()
        {
            return new ReadOnlyDictionary<string, string>(this.Configuration.DefaultHeader);
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        /// Get an author by his/her id 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="authorId">The id of the author you want to get</param>
        /// <returns>Author</returns>
        public Author GetAuthor (Guid? authorId)
        {
             ApiResponse<Author> localVarResponse = GetAuthorWithHttpInfo(authorId);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Get an author by his/her id 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="authorId">The id of the author you want to get</param>
        /// <returns>ApiResponse of Author</returns>
        public ApiResponse< Author > GetAuthorWithHttpInfo (Guid? authorId)
        {
            // verify the required parameter 'authorId' is set
            if (authorId == null)
                throw new ApiException(400, "Missing required parameter 'authorId' when calling AuthorsApi->GetAuthor");

            var localVarPath = "/api/v1/authors/{authorId}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json",
                "application/xml"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (authorId != null) localVarPathParams.Add("authorId", this.Configuration.ApiClient.ParameterToString(authorId)); // path parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetAuthor", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Author>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (Author) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(Author)));
        }

        /// <summary>
        /// Get an author by his/her id 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="authorId">The id of the author you want to get</param>
        /// <returns>Task of Author</returns>
        public async System.Threading.Tasks.Task<Author> GetAuthorAsync (Guid? authorId)
        {
             ApiResponse<Author> localVarResponse = await GetAuthorAsyncWithHttpInfo(authorId);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Get an author by his/her id 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="authorId">The id of the author you want to get</param>
        /// <returns>Task of ApiResponse (Author)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<Author>> GetAuthorAsyncWithHttpInfo (Guid? authorId)
        {
            // verify the required parameter 'authorId' is set
            if (authorId == null)
                throw new ApiException(400, "Missing required parameter 'authorId' when calling AuthorsApi->GetAuthor");

            var localVarPath = "/api/v1/authors/{authorId}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json",
                "application/xml"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (authorId != null) localVarPathParams.Add("authorId", this.Configuration.ApiClient.ParameterToString(authorId)); // path parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetAuthor", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Author>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (Author) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(Author)));
        }

        /// <summary>
        /// Get a list of authors 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>List&lt;Author&gt;</returns>
        public List<Author> GetAuthors ()
        {
             ApiResponse<List<Author>> localVarResponse = GetAuthorsWithHttpInfo();
             return localVarResponse.Data;
        }

        /// <summary>
        /// Get a list of authors 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>ApiResponse of List&lt;Author&gt;</returns>
        public ApiResponse< List<Author> > GetAuthorsWithHttpInfo ()
        {

            var localVarPath = "/api/v1/authors";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json",
                "application/xml"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);



            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetAuthors", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<List<Author>>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (List<Author>) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(List<Author>)));
        }

        /// <summary>
        /// Get a list of authors 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of List&lt;Author&gt;</returns>
        public async System.Threading.Tasks.Task<List<Author>> GetAuthorsAsync ()
        {
             ApiResponse<List<Author>> localVarResponse = await GetAuthorsAsyncWithHttpInfo();
             return localVarResponse.Data;

        }

        /// <summary>
        /// Get a list of authors 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <returns>Task of ApiResponse (List&lt;Author&gt;)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<List<Author>>> GetAuthorsAsyncWithHttpInfo ()
        {

            var localVarPath = "/api/v1/authors";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json",
                "application/xml"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);



            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetAuthors", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<List<Author>>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (List<Author>) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(List<Author>)));
        }

        /// <summary>
        /// Update an author 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="authorId">The id of the author to update</param>
        /// <param name="body"> (optional)</param>
        /// <returns>Author</returns>
        public Author UpdateAuthor (Guid? authorId, AuthorForUpdate body = null)
        {
             ApiResponse<Author> localVarResponse = UpdateAuthorWithHttpInfo(authorId, body);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Update an author 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="authorId">The id of the author to update</param>
        /// <param name="body"> (optional)</param>
        /// <returns>ApiResponse of Author</returns>
        public ApiResponse< Author > UpdateAuthorWithHttpInfo (Guid? authorId, AuthorForUpdate body = null)
        {
            // verify the required parameter 'authorId' is set
            if (authorId == null)
                throw new ApiException(400, "Missing required parameter 'authorId' when calling AuthorsApi->UpdateAuthor");

            var localVarPath = "/api/v1/authors/{authorId}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json",
                "application/xml"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (authorId != null) localVarPathParams.Add("authorId", this.Configuration.ApiClient.ParameterToString(authorId)); // path parameter
            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.PUT, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("UpdateAuthor", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Author>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (Author) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(Author)));
        }

        /// <summary>
        /// Update an author 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="authorId">The id of the author to update</param>
        /// <param name="body"> (optional)</param>
        /// <returns>Task of Author</returns>
        public async System.Threading.Tasks.Task<Author> UpdateAuthorAsync (Guid? authorId, AuthorForUpdate body = null)
        {
             ApiResponse<Author> localVarResponse = await UpdateAuthorAsyncWithHttpInfo(authorId, body);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Update an author 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="authorId">The id of the author to update</param>
        /// <param name="body"> (optional)</param>
        /// <returns>Task of ApiResponse (Author)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<Author>> UpdateAuthorAsyncWithHttpInfo (Guid? authorId, AuthorForUpdate body = null)
        {
            // verify the required parameter 'authorId' is set
            if (authorId == null)
                throw new ApiException(400, "Missing required parameter 'authorId' when calling AuthorsApi->UpdateAuthor");

            var localVarPath = "/api/v1/authors/{authorId}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json",
                "application/xml"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (authorId != null) localVarPathParams.Add("authorId", this.Configuration.ApiClient.ParameterToString(authorId)); // path parameter
            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.PUT, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("UpdateAuthor", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Author>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (Author) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(Author)));
        }

        /// <summary>
        /// Partially update an author Sample request (this request updates the author&#x27;s **first name**)                              PATCH /authors/authorId              [                   {                      \&quot;op\&quot;: \&quot;replace\&quot;,                       \&quot;path\&quot;: \&quot;/firstname\&quot;,                       \&quot;value\&quot;: \&quot;new first name\&quot;                   }               ]
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="authorId">The id of the author you want to get</param>
        /// <param name="body"> (optional)</param>
        /// <returns>Author</returns>
        public Author UpdateAuthor_0 (Guid? authorId, List<Operation> body = null)
        {
             ApiResponse<Author> localVarResponse = UpdateAuthor_0WithHttpInfo(authorId, body);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Partially update an author Sample request (this request updates the author&#x27;s **first name**)                              PATCH /authors/authorId              [                   {                      \&quot;op\&quot;: \&quot;replace\&quot;,                       \&quot;path\&quot;: \&quot;/firstname\&quot;,                       \&quot;value\&quot;: \&quot;new first name\&quot;                   }               ]
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="authorId">The id of the author you want to get</param>
        /// <param name="body"> (optional)</param>
        /// <returns>ApiResponse of Author</returns>
        public ApiResponse< Author > UpdateAuthor_0WithHttpInfo (Guid? authorId, List<Operation> body = null)
        {
            // verify the required parameter 'authorId' is set
            if (authorId == null)
                throw new ApiException(400, "Missing required parameter 'authorId' when calling AuthorsApi->UpdateAuthor_0");

            var localVarPath = "/api/v1/authors/{authorId}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json-patch+json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json",
                "application/xml"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (authorId != null) localVarPathParams.Add("authorId", this.Configuration.ApiClient.ParameterToString(authorId)); // path parameter
            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) this.Configuration.ApiClient.CallApi(localVarPath,
                Method.PATCH, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("UpdateAuthor_0", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Author>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (Author) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(Author)));
        }

        /// <summary>
        /// Partially update an author Sample request (this request updates the author&#x27;s **first name**)                              PATCH /authors/authorId              [                   {                      \&quot;op\&quot;: \&quot;replace\&quot;,                       \&quot;path\&quot;: \&quot;/firstname\&quot;,                       \&quot;value\&quot;: \&quot;new first name\&quot;                   }               ]
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="authorId">The id of the author you want to get</param>
        /// <param name="body"> (optional)</param>
        /// <returns>Task of Author</returns>
        public async System.Threading.Tasks.Task<Author> UpdateAuthor_0Async (Guid? authorId, List<Operation> body = null)
        {
             ApiResponse<Author> localVarResponse = await UpdateAuthor_0AsyncWithHttpInfo(authorId, body);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Partially update an author Sample request (this request updates the author&#x27;s **first name**)                              PATCH /authors/authorId              [                   {                      \&quot;op\&quot;: \&quot;replace\&quot;,                       \&quot;path\&quot;: \&quot;/firstname\&quot;,                       \&quot;value\&quot;: \&quot;new first name\&quot;                   }               ]
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="authorId">The id of the author you want to get</param>
        /// <param name="body"> (optional)</param>
        /// <returns>Task of ApiResponse (Author)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<Author>> UpdateAuthor_0AsyncWithHttpInfo (Guid? authorId, List<Operation> body = null)
        {
            // verify the required parameter 'authorId' is set
            if (authorId == null)
                throw new ApiException(400, "Missing required parameter 'authorId' when calling AuthorsApi->UpdateAuthor_0");

            var localVarPath = "/api/v1/authors/{authorId}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new List<KeyValuePair<String, String>>();
            var localVarHeaderParams = new Dictionary<String, String>(this.Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json-patch+json"
            };
            String localVarHttpContentType = this.Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json",
                "application/xml"
            };
            String localVarHttpHeaderAccept = this.Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (authorId != null) localVarPathParams.Add("authorId", this.Configuration.ApiClient.ParameterToString(authorId)); // path parameter
            if (body != null && body.GetType() != typeof(byte[]))
            {
                localVarPostBody = this.Configuration.ApiClient.Serialize(body); // http body (model) parameter
            }
            else
            {
                localVarPostBody = body; // byte array
            }


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await this.Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.PATCH, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("UpdateAuthor_0", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<Author>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (Author) this.Configuration.ApiClient.Deserialize(localVarResponse, typeof(Author)));
        }

    }
}
